---
role:
  install:
    - command: curl -sSL https://rpm.nodesource.com/setup_8.x | sudo bash -
      # Or https://rpm.nodesource.com/setup_10.x
      os: ["centos"]
  pkg:
    - name: nodejs
      os: ["!darwin"]
    - name: npm
      os: ["!darwin"]
    - name: node
      os: ["darwin"]
    # - yarn
  link:
    - .bowerrc
    # - .tern-project
  # template:
  #   - .npmrc.tpl
  #   # vars:
  #     # npm_user
  #     # npm_email
  #     # npm_prefix
  post_install:
    - node --version
    - npm --version
