---
role:
  pkg:
    - name: curl
      os: ["debian"]
    - name: gpg
      os: ["debian"]
    - name: nodejs
      os: ["!darwin"]
    - name: npm
      os: ["!darwin"]
    - name: node
      os: ["darwin"]
    # - yarn
  link:
    - .bowerrc
    # - .tern-project
  # template:
  #   - .npmrc.tpl
  #   # vars:
  #     # npm_user
  #     # npm_email
  #     # npm_prefix
  # env:
  #   NODE_VERSION: 8 # 10
  install:
    # https://nodejs.org/en/download/package-manager
    - command: curl -sSL https://rpm.nodesource.com/setup_8.x | sudo bash -
      os: ["centos"]
    - command: curl -sSL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      os: ["debian"]
  post_install:
    - node --version
    - npm --version
