---
role:
  install:
    # https://nodejs.org/en/download/package-manager
    # - command: curl -sSL https://rpm.nodesource.com/setup_8.x | sudo bash -
    #   os: ["centos"]
    - command: curl -sSL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      # sudo apt-get install -qqy curl gnupg
      #curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      #echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      #sudo apt-get update && sudo apt-get install yarn
      os: ["debian"]
  pkg:
    - name: node
      os: ["darwin"]
    - name: ["nodejs", "npm"]
      os: ["!android", "!darwin"]
    - name: nodejs
      os: ["android"]
    # - yarn
  link:
    - .bowerrc
    # - .tern-project
  # template:
  #   - .npmrc.tpl
  #   # vars:
  #     # npm_user
  #     # npm_email
  #     # npm_prefix
  # env:
  #   NODE_VERSION: 8 # 10
  post_install:
    - node --version
    - npm --version
